// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGpv9ic4y00jThuq8XIahk9j7gBDCj18',
    appId: '1:627934215135:web:ecc6c94878575ee152a26a',
    messagingSenderId: '627934215135',
    projectId: 'chatty-2cf93',
    authDomain: 'chatty-2cf93.firebaseapp.com',
    storageBucket: 'chatty-2cf93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARMXHV1vnIOIknRiBtB6fEdkvQBdq17as',
    appId: '1:627934215135:android:4d582b0212d0772d52a26a',
    messagingSenderId: '627934215135',
    projectId: 'chatty-2cf93',
    storageBucket: 'chatty-2cf93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39NHa2VFVkdUW7feHKKRaspRIxgz3NgM',
    appId: '1:627934215135:ios:f977b1b8829c062d52a26a',
    messagingSenderId: '627934215135',
    projectId: 'chatty-2cf93',
    storageBucket: 'chatty-2cf93.appspot.com',
    iosClientId: '627934215135-am1r0o67l4f97v6a8oqdn7ul12u9pcsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatHelpProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB39NHa2VFVkdUW7feHKKRaspRIxgz3NgM',
    appId: '1:627934215135:ios:551824ac2af5edb652a26a',
    messagingSenderId: '627934215135',
    projectId: 'chatty-2cf93',
    storageBucket: 'chatty-2cf93.appspot.com',
    iosClientId: '627934215135-e3qjlrmltqac1r3hgkrfo1jrmf8jprbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatHelpProject.RunnerTests',
  );
}
